project:
  type: book

book:
  title: "Introducción a la Estadística usando R Notebooks"
  author: "Mario Santana"
  date: last_modified
  date-format: "DD/MM/YYYY"
  sidebar:
    search: true  # Esto activa el buscador automático
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_descriptiva.qmd
    - 03_inferencia.qmd
    - 04_anova.qmd
    - 05_regresion.qmd
    - references.qmd
    
crossref:
  fig-title: "Figura" # Etiqueta prefijo
  fig-prefix: "Fig." # Cómo se cita en el texto

bibliography: references.bib

format:
  html:
    theme:
      - cerulean
      - brand
    toc: true
  # pdf:
  #   prefer-html: true
  #   documentclass: scrreprt



